master:
  image: epahomov/docker-spark
  tty: true
  command: /start-master.sh
  ports:
    - "8080:8080"
    - "7077:7077"

worker:
  image: epahomov/docker-spark
  tty: true
  command: /start-worker.sh
  ports:
    - "8081:8081"
  links:
    - master:spark_master